import { Listing, CityInfo } from "./types";

export const SEED_LISTINGS: Listing[] = [
  {
    id: "1",
    name: "Twice the Ice - Roswell",
    category_primary: "ice-vending",
    category_secondary: ["water-refill"],
    address: "1025 Alpharetta St",
    city: "Roswell",
    state: "GA",
    zip: "30075",
    lat: 34.0393,
    lng: -84.3613,
    phone: "(770) 555-0101",
    website: "https://twicetheice.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash"],
    has_water_refill: true,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: true,
    source_name: "Twice the Ice",
    source_url: "https://twicetheice.com/locations",
    source_priority: 1,
    last_verified_at: "2025-12-01",
    status: "active",
    photos: [],
    rating: 4.5,
    density_score: 8,
  },
  {
    id: "2",
    name: "Kooler Ice - Marietta",
    category_primary: "ice-vending",
    category_secondary: ["water-refill"],
    address: "640 Cobb Pkwy S",
    city: "Marietta",
    state: "GA",
    zip: "30060",
    lat: 33.9304,
    lng: -84.5467,
    phone: "(770) 555-0102",
    website: "https://koolerice.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash"],
    has_water_refill: true,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: false,
    convenience_store_nearby: true,
    source_name: "Kooler Ice",
    source_url: "https://koolerice.com/locations",
    source_priority: 1,
    last_verified_at: "2025-11-15",
    status: "active",
    photos: [],
    rating: 4.2,
    density_score: 6,
  },
  {
    id: "3",
    name: "Ice House America - Decatur",
    category_primary: "ice-vending",
    category_secondary: [],
    address: "315 W Ponce De Leon Ave",
    city: "Decatur",
    state: "GA",
    zip: "30030",
    lat: 33.7748,
    lng: -84.2963,
    phone: "(404) 555-0103",
    website: "https://icehouseamerica.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: false,
    source_name: "Ice House America",
    source_url: "https://icehouseamerica.com",
    source_priority: 2,
    last_verified_at: "2025-10-20",
    status: "active",
    photos: [],
    rating: 4.0,
    density_score: 7,
  },
  {
    id: "4",
    name: "Airgas Dry Ice - Atlanta",
    category_primary: "dry-ice",
    category_secondary: [],
    address: "1945 The Exchange SE",
    city: "Atlanta",
    state: "GA",
    zip: "30339",
    lat: 33.8651,
    lng: -84.4625,
    phone: "(770) 555-0104",
    website: "https://airgas.com",
    hours: "Mon-Fri 7AM-5PM, Sat 8AM-12PM",
    open_24h: false,
    payment_types: ["card", "cash"],
    has_water_refill: false,
    has_dry_ice: true,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: false,
    convenience_store_nearby: true,
    source_name: "Airgas",
    source_url: "https://airgas.com/store-locator",
    source_priority: 1,
    last_verified_at: "2025-12-10",
    status: "active",
    photos: [],
    rating: 4.3,
    density_score: 5,
  },
  {
    id: "5",
    name: "AmeriGas Propane - Lawrenceville",
    category_primary: "propane-refill",
    category_secondary: ["propane-exchange"],
    address: "750 Collins Hill Rd",
    city: "Lawrenceville",
    state: "GA",
    zip: "30043",
    lat: 33.9562,
    lng: -84.0027,
    phone: "(678) 555-0105",
    website: "https://amerigas.com",
    hours: "Mon-Fri 8AM-5PM, Sat 9AM-1PM",
    open_24h: false,
    payment_types: ["card", "cash"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: true,
    has_propane_exchange: true,
    alcohol_license_nearby: false,
    convenience_store_nearby: false,
    source_name: "AmeriGas",
    source_url: "https://amerigas.com/locations",
    source_priority: 1,
    last_verified_at: "2025-11-05",
    status: "active",
    photos: [],
    rating: 4.1,
    density_score: 3,
  },
  {
    id: "6",
    name: "U-Haul Propane - Kennesaw",
    category_primary: "propane-refill",
    category_secondary: [],
    address: "2935 Canton Rd",
    city: "Kennesaw",
    state: "GA",
    zip: "30144",
    lat: 34.0311,
    lng: -84.5999,
    phone: "(770) 555-0106",
    website: "https://uhaul.com",
    hours: "Mon-Sat 7AM-7PM, Sun 9AM-5PM",
    open_24h: false,
    payment_types: ["card", "cash", "mobile"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: true,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: true,
    source_name: "U-Haul",
    source_url: "https://uhaul.com/locations",
    source_priority: 2,
    last_verified_at: "2025-10-15",
    status: "active",
    photos: [],
    rating: 3.9,
    density_score: 5,
  },
  {
    id: "7",
    name: "Twice the Ice - Savannah",
    category_primary: "ice-vending",
    category_secondary: ["water-refill"],
    address: "4511 Habersham St",
    city: "Savannah",
    state: "GA",
    zip: "31405",
    lat: 32.0322,
    lng: -81.1206,
    phone: "(912) 555-0107",
    website: "https://twicetheice.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash"],
    has_water_refill: true,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: true,
    source_name: "Twice the Ice",
    source_url: "https://twicetheice.com/locations",
    source_priority: 1,
    last_verified_at: "2025-12-01",
    status: "active",
    photos: [],
    rating: 4.4,
    density_score: 6,
  },
  {
    id: "8",
    name: "Penguin Dry Ice - Augusta",
    category_primary: "dry-ice",
    category_secondary: [],
    address: "2215 Wrightsboro Rd",
    city: "Augusta",
    state: "GA",
    zip: "30904",
    lat: 33.4844,
    lng: -82.0128,
    phone: "(706) 555-0108",
    website: "https://penguindryice.com",
    hours: "Mon-Fri 8AM-5PM",
    open_24h: false,
    payment_types: ["card"],
    has_water_refill: false,
    has_dry_ice: true,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: false,
    convenience_store_nearby: true,
    source_name: "Penguin Dry Ice",
    source_url: "https://penguindryice.com",
    source_priority: 2,
    last_verified_at: "2025-09-20",
    status: "active",
    photos: [],
    rating: 4.0,
    density_score: 2,
  },
  {
    id: "9",
    name: "Kooler Ice - Athens",
    category_primary: "ice-vending",
    category_secondary: ["water-refill"],
    address: "196 Alps Rd",
    city: "Athens",
    state: "GA",
    zip: "30606",
    lat: 33.9369,
    lng: -83.4074,
    phone: "(706) 555-0109",
    website: "https://koolerice.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash"],
    has_water_refill: true,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: true,
    source_name: "Kooler Ice",
    source_url: "https://koolerice.com/locations",
    source_priority: 1,
    last_verified_at: "2025-11-10",
    status: "active",
    photos: [],
    rating: 4.6,
    density_score: 4,
  },
  {
    id: "10",
    name: "Ice Merchant - Macon",
    category_primary: "ice-vending",
    category_secondary: [],
    address: "3780 Riverside Dr",
    city: "Macon",
    state: "GA",
    zip: "31210",
    lat: 32.8651,
    lng: -83.7099,
    phone: "(478) 555-0110",
    website: "https://icemerchant.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: false,
    convenience_store_nearby: false,
    source_name: "Ice Merchant",
    source_url: "https://icemerchant.com",
    source_priority: 2,
    last_verified_at: "2025-10-01",
    status: "active",
    photos: [],
    rating: 3.8,
    density_score: 2,
  },
  {
    id: "11",
    name: "QuikTrip - Peachtree City",
    category_primary: "convenience-store",
    category_secondary: ["beer-drinks"],
    address: "200 Hwy 74 N",
    city: "Peachtree City",
    state: "GA",
    zip: "30269",
    lat: 33.4010,
    lng: -84.5826,
    phone: "(770) 555-0111",
    website: "https://quiktrip.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash", "mobile"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: true,
    alcohol_license_nearby: true,
    convenience_store_nearby: false,
    source_name: "QuikTrip",
    source_url: "https://quiktrip.com/locations",
    source_priority: 3,
    last_verified_at: "2025-12-05",
    status: "active",
    photos: [],
    rating: 4.3,
    density_score: 7,
  },
  {
    id: "12",
    name: "Twice the Ice - Columbus",
    category_primary: "ice-vending",
    category_secondary: ["water-refill"],
    address: "5601 Veterans Pkwy",
    city: "Columbus",
    state: "GA",
    zip: "31904",
    lat: 32.5112,
    lng: -84.9474,
    phone: "(706) 555-0112",
    website: "https://twicetheice.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash"],
    has_water_refill: true,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: false,
    convenience_store_nearby: true,
    source_name: "Twice the Ice",
    source_url: "https://twicetheice.com/locations",
    source_priority: 1,
    last_verified_at: "2025-11-20",
    status: "active",
    photos: [],
    rating: 4.1,
    density_score: 3,
  },
  {
    id: "13",
    name: "AmeriGas Propane - Valdosta",
    category_primary: "propane-refill",
    category_secondary: ["propane-exchange"],
    address: "1105 N St Augustine Rd",
    city: "Valdosta",
    state: "GA",
    zip: "31601",
    lat: 30.8571,
    lng: -83.2785,
    phone: "(229) 555-0113",
    website: "https://amerigas.com",
    hours: "Mon-Fri 8AM-5PM",
    open_24h: false,
    payment_types: ["card", "cash"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: true,
    has_propane_exchange: true,
    alcohol_license_nearby: false,
    convenience_store_nearby: false,
    source_name: "AmeriGas",
    source_url: "https://amerigas.com/locations",
    source_priority: 1,
    last_verified_at: "2025-10-30",
    status: "active",
    photos: [],
    rating: 4.0,
    density_score: 1,
  },
  {
    id: "14",
    name: "Kooler Ice - Gainesville",
    category_primary: "ice-vending",
    category_secondary: ["water-refill"],
    address: "820 Green St NW",
    city: "Gainesville",
    state: "GA",
    zip: "30501",
    lat: 34.3015,
    lng: -83.8346,
    phone: "(770) 555-0114",
    website: "https://koolerice.com",
    hours: "24/7",
    open_24h: true,
    payment_types: ["card", "cash"],
    has_water_refill: true,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: true,
    source_name: "Kooler Ice",
    source_url: "https://koolerice.com/locations",
    source_priority: 1,
    last_verified_at: "2025-11-25",
    status: "active",
    photos: [],
    rating: 4.7,
    density_score: 5,
  },
  {
    id: "15",
    name: "Tower Beer Wine & Spirits - Atlanta",
    category_primary: "package-store",
    category_secondary: ["beer-drinks"],
    address: "2161 Piedmont Rd NE",
    city: "Atlanta",
    state: "GA",
    zip: "30324",
    lat: 33.8117,
    lng: -84.3655,
    phone: "(404) 555-0115",
    website: "https://towerwinespirits.com",
    hours: "Mon-Sat 9AM-11PM, Sun 12:30PM-8PM",
    open_24h: false,
    payment_types: ["card", "cash", "mobile"],
    has_water_refill: false,
    has_dry_ice: false,
    has_propane_refill: false,
    has_propane_exchange: false,
    alcohol_license_nearby: true,
    convenience_store_nearby: true,
    source_name: "GA Alcohol License",
    source_url: "https://dor.georgia.gov",
    source_priority: 1,
    last_verified_at: "2025-12-01",
    status: "active",
    photos: [],
    rating: 4.8,
    density_score: 9,
  },
];

export const GA_CITIES: CityInfo[] = [
  { name: "Atlanta", slug: "atlanta-ga", lat: 33.749, lng: -84.388, county: "Fulton", population: 498715 },
  { name: "Savannah", slug: "savannah-ga", lat: 32.0809, lng: -81.0912, county: "Chatham", population: 147780 },
  { name: "Augusta", slug: "augusta-ga", lat: 33.4735, lng: -81.9748, county: "Richmond", population: 202081 },
  { name: "Columbus", slug: "columbus-ga", lat: 32.4610, lng: -84.9877, county: "Muscogee", population: 206922 },
  { name: "Macon", slug: "macon-ga", lat: 32.8407, lng: -83.6324, county: "Bibb", population: 157346 },
  { name: "Roswell", slug: "roswell-ga", lat: 34.0232, lng: -84.3616, county: "Fulton", population: 94786 },
  { name: "Athens", slug: "athens-ga", lat: 33.9519, lng: -83.3576, county: "Clarke", population: 127064 },
  { name: "Marietta", slug: "marietta-ga", lat: 33.9526, lng: -84.5499, county: "Cobb", population: 60972 },
  { name: "Kennesaw", slug: "kennesaw-ga", lat: 34.0234, lng: -84.6155, county: "Cobb", population: 34077 },
  { name: "Decatur", slug: "decatur-ga", lat: 33.7748, lng: -84.2963, county: "DeKalb", population: 24928 },
  { name: "Lawrenceville", slug: "lawrenceville-ga", lat: 33.9562, lng: -83.9880, county: "Gwinnett", population: 30798 },
  { name: "Valdosta", slug: "valdosta-ga", lat: 30.8327, lng: -83.2785, county: "Lowndes", population: 56457 },
  { name: "Gainesville", slug: "gainesville-ga", lat: 34.2979, lng: -83.8241, county: "Hall", population: 43435 },
  { name: "Peachtree City", slug: "peachtree-city-ga", lat: 33.3968, lng: -84.5957, county: "Fayette", population: 38364 },
  { name: "Alpharetta", slug: "alpharetta-ga", lat: 34.0754, lng: -84.2941, county: "Fulton", population: 65818 },
];

export const GA_CATEGORIES = [
  { slug: "ice-vending-machines", label: "Ice Vending Machines", category: "ice-vending" as const },
  { slug: "water-refill-stations", label: "Water Refill Stations", category: "water-refill" as const },
  { slug: "dry-ice", label: "Dry Ice Sellers", category: "dry-ice" as const },
  { slug: "propane-refill", label: "Propane Refill & Exchange", category: "propane-refill" as const },
  { slug: "beer-near-ice", label: "Beer & Drinks Near Ice", category: "beer-drinks" as const },
  { slug: "convenience-stores", label: "Convenience Stores", category: "convenience-store" as const },
];
